version: "3.7"

services:
  productDb:
    container_name: productDb
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: productDb
    ports:
      - "3306:3306"
  paymentDb:
    container_name: paymentDb
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: paymentDb
    ports:
      - "3307:3306"
  orderDb:
    container_name: orderDb
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orderDb
    ports:
      - "3308:3306"

volumes:
  mysql_data: