server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296
  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICEs
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/orderServiceFallback
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: PAYMENT-SERVICE
                fallbackuri: forward:/paymentServiceFallback
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/productServiceFallback
okta:
  oauth2:
    issuer: https://dev-84928916.okta.com/oauth2/default
    audience: api://default
    client-id: xxxx
    client-secret: xxxxxx
    scopes: openid, profile, email, offline_access

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: Product Service
        url: /product/api-docs
      - name: Order Service
        url: /order/api-docs
      - name: Payment Service
        url: /payment/api-docs
