server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    gateway:
      mvc:
        routes:
          - id: employee-service
            uri: lb://employee-service
            predicates:
              - Path=/employee/**
          - id: department-service
            uri: lb://department-service
            predicates:
              - Path=/department/**



  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://dev-16235276.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: openid, profile, email, offline_access
            client-id: 0oagp6pjv1sYxCEvk5d7
            client-secret: bT1k0EG10HWvwCaG9auTxzALcQoA1wCzNaUQU3EgDqDiNru3VmXjJg2lx6J3fJrd
  main:
    allow-bean-definition-overriding: true


okta:
  oauth2:
    issuer: https://dev-16235276.okta.com/oauth2/default
    audience: api://default
    client-id: 0oagp6pjv1sYxCEvk5d7
    client-secret: bT1k0EG10HWvwCaG9auTxzALcQoA1wCzNaUQU3EgDqDiNru3VmXjJg2lx6J3fJrd