server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderDb?allowPublicKeyRetrieval=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://dev-84928916.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oaezuf0meAwuh0F25d7
            client-secret: GO953Yi1FyJQsSMpSHagq6SEMEiQ9Z77JkHph9e0aYPbdTKavTQWqiLi94Ze94JI

management:
  tracing:
    sampling:
      probability: 1.0
