server:
  port: 8082

spring:
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296



  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://dev-16235276.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: openid, profile, email, offline_access
            client-id: xxxx
            client-secret: xxxxx
    allow-bean-definition-overriding: true


okta:
  oauth2:
    issuer: https://dev-16235276.okta.com/oauth2/default
    audience: api://default
    client-id: xxxxx
    client-secret: xxxxx

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html