server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/orderDb?allowPublicKeyRetrieval=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: ORDER-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    defaultZone: { EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka }