server:
  port: 8082

spring:
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}
          audiences: ${AUTH0_AUDIENCE:http://springboot-microservices-api}
      client:
        registration:
          internal-client:
            provider: auth0
            authorization-grant-type: client_credentials
            scope: openid,profile,email
            client-id: ${AUTH0_M2M_CLIENT_ID}
            client-secret: ${AUTH0_M2M_CLIENT_SECRET}
        provider:
          auth0:
            issuer-uri: ${AUTH0_ISSUER_URI}
            token-uri: ${AUTH0_ISSUER_URI}oauth/token
      resourceserver:
        opaquetoken:
          client-id: ${AUTH0_M2M_CLIENT_ID}
          client-secret: ${AUTH0_M2M_CLIENT_SECRET}
          introspection-uri: ${AUTH0_ISSUER_URI}oauth/introspect
    cloud:
      openfeign:
        oauth2:
          clientRegistrationId: internal-client
          audience: ${AUTH0_AUDIENCE:http://springboot-microservices-api}
    allow-bean-definition-overriding: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html